### ISSUE TITLE
clipmenud.service: too eager to start on some machine

### ISSUE THREAD

**Issue by randomizedthinking** [cdown/clipmenu#101]
I am using clipmenu for some time and it works out greatly.

One item I notice is that the clipmenud.service might be too eager to start during system start-up time on some machines. Ideally, it should wait till xorg starts, yet on one of my machine, the system always tries to start clipmenud service very early: it slows down the system startup quite a bit.

Would be great to have it up only the xserver is up. I did some research yet didn't find a nice solution.

**Comment by cdown** [comment]
Yes, it depends on xorg, but there's no standardised target for this (`graphical.target` is related, but happens at the wrong time during initialisation). You need to set it up as appropriate in your environment if you are using `enable` instead of manually starting services from your WM or xinitrc.

**Comment by cdown** [comment]
Ah, this is made worse by `RestartSec=0`. I'm changing this to be 500ms, the same as the default CM_SLEEP.

**Comment by cdown** [comment]
I think this should resolve everything that's resolvable, but let me know if you still have questions. Thanks!
