### ISSUE TITLE
Clean shutdown

### ISSUE THREAD

**Issue by AckslD** [cdown/clipmenu#193]
When shutting down my system it takes some time since some process is not shutting down properly and I suspect it is `clipmenud`, since when I look at the last boot log I see many:
```
Aug 24 19:49:39 l390 clipmenud[1628470]: Failed creating new xdo instance.
Aug 24 19:49:39 l390 clipmenud[1628583]: xsel: Can't open display: (null)
Aug 24 19:49:39 l390 clipmenud[1628583]: : Connection refused
Aug 24 19:49:39 l390 clipmenud[1628587]: Can't open X display
```
which I suspect is because the X session is already closed.

Any idea how to make the shutdown better for clipmenu?

**Comment by cdown** [comment]
I doubt it's clipmenud, because when you send SIGTERM to us, we're will immediately close. The reason you see those messages is more likely because you haven't set up your X services to shut down when X shuts down (eg. by having X shutdown start a target).

If `systemctl --user stop clipmenud` works normally, then your problem is going to be elsewhere.

**Comment by AckslD** [comment]
I see, thanks for you reply @cdown! I'll try to investigate further

**Comment by cdown** [comment]
Closing since this applies to the old bash version, but please feel free to reopen if there are problems with clipmenu 7
