### ISSUE TITLE
Is There A Way To Pass A Config Path For Rofi In Clipmenu?

### ISSUE THREAD

**Issue by MuntasirSZN** [cdown/clipmenu#233]
I installed it today, for getting shot in head because of cliphist. So, i wanna pass some args to rofi, like, i have a config to use, ~/.config/rofi-clipboard.rasi, its not default, my default one is different. So How to do that?

**Comment by vejkse** [comment]
With clipmenu 6, you could use this wrapper (I don’t have rofi to test it, but a similar one for fzf works):
```bash
#!/usr/bin/bash

rofi_clipboard() {
  rofi -config "$HOME/.config/rofi-clipboard.rasi"
}
export -f rofi_clipboard

env CM_LAUNCHER=rofi_clipboard clipmenu
```

For the in-development clipmenu 7, this doesn’t work and I don’t know how to make it work.  Maybe this is not yet implemented.

**Comment by MuntasirSZN** [comment]
Works on latest clipmenu version, just hooked up a keyboard shortcut for it. Thanks @vejkse

**Comment by vejkse** [comment]
For the future clipmenu 7, since it is not a bash script any more, it can’t use a bash function as `CM_LAUNCHER`, so you will have to make `rofi_clipboard` into its own separate script installed in your `PATH`:
```sh
#!/usr/bin/sh

rofi -config "$HOME/.config/rofi-clipboard.rasi"
```
and then you should be able to use `env CM_LAUNCHER=rofi_clipboard clipmenu`.

(This should already work with the current clipmenu, so if you make that change now, you won’t have a broken configuration when the new version comes.)
