### ISSUE TITLE
Synchronize clipboards when copying

### ISSUE THREAD

**Issue by simao** [cdown/clipmenu#65]
Hi,

I would like to suggest this feature, some other clipboard managers implement it. 

When this feature is on, and the user copies some text to the primary clipboard, the text is also transferred to the the secondary clipboard and vice-versa. I think this would avoid having to call clipmenu if a user selects somethig with clipboard selection and then wants to paste it with the keyboard instead of pressing mouse-middle click for example.

Also I want to thank you for working on clipmenu, this is really great and integrates very well with clipmenu. 
This is better than any other clipboard manager I tried.

**Comment by cdown** [comment]
If I understand correctly, I think your needs should be met by `autocutsel`, right? :-)

https://www.nongnu.org/autocutsel/

**Comment by simao** [comment]
From the description that indeed looks like what I want, thanks a lot! but it looks like some clips vanish by the time I select them with clipmenu, I will investigate further.

**Comment by cdown** [comment]
I think realistically I'm unlikely to implement this, and would rather leave it to `autocutsel` and the like. Let me know if that doesn't work out in conjunction with clipmenu, though. :-)

**Comment by tblancher** [comment]
With autocutsel and clipmenud you basically have two daemons that manage the clipboard.  It works well enough, but autocutsel hasn't been updated since 2014.  Ideally clipmenud would support an environment variable that enables the synchronization of the PRIMARY and CLIPBOARD buffers.

Back when I started on Linux and Xorg, I liked the separation between the two buffers (I could copy a username with the PRIMARY selection, and copy the password with the CLIPBOARD selection).  However, I now work on macOS and Windows machines that only have the one clipboard/paste buffer, and I rely heavily on a clipboard manager in those environments.  It's too much of a context switch in my brain to remember that there are two buffers in Linux/Xorg.  Having an environment variable like CM_SYNC_BUFFERS or CM_UNIFIED would mean I don't have to rely on potentially broken and unmaintained software to achieve a unified clipboard.

I don't have time at the moment, but I may be able to work on a PR tomorrow evening to add this as an option.

**Comment by cdown** [comment]
#126 may do what you want.

**Comment by BachoSeven** [comment]
> It works well enough, but autocutsel hasn't been updated since 2014.

@tblancher FWIW, 2021 saw a new `autocutsel` release: https://github.com/sigmike/autocutsel/releases/tag/0.10.1
