### ISSUE TITLE
xset logfile

### ISSUE THREAD

**Issue by namitjuneja** [cdown/clipmenu#66]
In many devices xset when used with --logfile /dev/stderr fails the clipmenu script because of lack of permissions. New users might not be able to debug this. It would be a better idea to altogether skip this argument and let the logfile remain in its default location.

**Comment by cdown** [comment]
What version of clipmenu is this? What does `stat -L /dev/stderr` say?

On a sane init system, `/dev/stderr` should be a symlink to `/proc/self/fd/2`, which should certainly be writable by xsel as launched by clipmenud.

If the issue is that `/dev/stderr` doesn't exist, we shouldn't write to it at all (see f576a116fd).

**Comment by cdown** [comment]
Closing due to no response.
